version: "3"
services:

  demo-selenium:
    image:  selenium/hub:3.4.0

  demo-chrome:
    image:  selenium/node-chrome-debug
    ports:
      - ${DOCKER_COMPOSE_DEMO_VNC_PORT}:5900
    environment:
        - HUB_PORT_4444_TCP_ADDR=demo-selenium
        - HUB_PORT_4444_TCP_PORT=4444